### ISSUE TITLE
Sugar 1.6.1

### ISSUE THREAD

**Issue by VezirChess** [Zerbinati/SugaR#1]
In my tests, Sugar 1.6.1 is clearly stronger than that 4 version available in this repository.
Can you upload it again?( With Source Code of course )

**Comment by Zerbinati** [comment]
It is necessary to wait for the next release.

**Comment by sweetypg392** [comment]
? Nxt release? You did not anything during these two weeks, Sugar don't need MCTS mode, make an old repository pls
