### ISSUE TITLE
Compile error in search.cpp

### ISSUE THREAD

**Issue by ScallyBag** [Zerbinati/SugaR#107]
Hi,

My latest Raspberry Pi compile for PicoChess failed with:

search.cpp: In function ‘Value {anonymous}::search(Position&, Search::Stack*, Value, Value, Depth, bool)’:
search.cpp:905:17: error: found ‘:’ in nested-name-specifier, expected ‘::’
            + std:min(int(eval - beta) / NMPvalue, 3)) * ONE_PLY;

Adding the extra colon in search.cpp fixes it.

Thanks,

Al.

**Comment by Zerbinati** [comment]
Hi cooper
fix to:
+ std::min(int(eval - beta) / NMPvalue, 3)) * ONE_PLY;

https://github.com/Zerbinati/SugaR/commit/b08d5ede2f387ab4ae2445f293a2e964fa0c6024
