### ISSUE TITLE
updating the S_MCTSL_learning.7z 

### ISSUE THREAD

**Issue by greenbean52** [Zerbinati/SugaR#3]
I'm working on updating the
S_MCTSL_learning.7z 

With the runtime mine has done. 
Over 3 days on 100 alphazero games to depth 40 and 80 for endgame
900 up to move 12
900 up to move 14
900 up to move 42
900 still processing..

I need that merger.exe to make the 
S_MCTSL_learning.7z

#2 
I also need the answer to does experience.bin
Reflect the #2 hash#.bin in experience.bin

I will be uploading my forked 
https://github.com/greenbean52/SugaR
S_MCTSL_learning.7z
With copy from two sources and replace
All smaller files until then. 

With a pull request. When file is ready. 
But I'm new to this and I'm at this point just guessing that's how its done.

Cheers!
Greenbean52

**Comment by Zerbinati** [comment]
Do not rely on this code, it will be updated a little bit and will also include the implementation of the automatic merging of BIN files.
Regards
M.Z
