### ISSUE TITLE
Required instrunction about building in Windows.

### ISSUE THREAD

**Issue by Kozlov-Sergey-Aleksandrovitch** [Zerbinati/SugaR#4]
Required instrunction about building in Windows.

Visual Studio 2015 failed to create correctly project file for x64 configuration.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Exception on "piece_on(from)" in infinite analys on command "go infinite" in start position in line "assert(pc != NO_PIECE);".

/// Position::see_ge (Static Exchange Evaluation Greater or Equal) tests if the
/// SEE value of move is greater or equal to the given threshold. We'll use an
/// algorithm similar to alpha-beta pruning with a null window.

bool Position::see_ge(Move m, Value threshold) const {

  assert(is_ok(m));

  // Only deal with normal moves, assume others pass a simple see
  if (type_of(m) != NORMAL)
      return VALUE_ZERO >= threshold;

  Square from = from_sq(m), to = to_sq(m);
  PieceType nextVictim = type_of(piece_on(from));
  Color stm = ~color_of(piece_on(from)); // First consider opponent's move

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
This is why program does not work.

**Comment by Zerbinati** [comment]
Simply copy "DLL files" the C: \ Windows \ System32

2017-10-05 8:59 GMT+02:00 Kozlov Sergey Aleksandrovitch <
notifications@github.com>:

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Now i have build and the program works well.
