### ISSUE TITLE
Option handling and UCI compliance

### ISSUE THREAD

**Issue by alwey** [Zerbinati/SugaR#43]
When I tested SugaR with cutechess I noticed that it causes a series of warning messages when options are set. SugaR acknowledges an option change by issuing an `option` command on the UCI interface. This is unexpected, so please consider changing this.

A UCI compliant way to provide an acknowledgement is to use `info string option`. This is what Komodo does when an option is set, while Stockfish remains silent.

```
--- a/source/uci.cpp
+++ b/source/uci.cpp
@@ -98,10 +98,10 @@ namespace {
     if (Options.count(name))
        {
         Options[name] = value;
-               sync_cout << "option " << name << " set to " << value << sync_en
+               sync_cout << "info string option " << name << " set to " << valu
        }
     else
-        sync_cout << "No such option: " << name << sync_endl;
+        sync_cout << "info string No such option: " << name << sync_endl;
   }


```

;-)

**Comment by Zerbinati** [comment]
@alwey Simplifying ..
    if (Options.count(name))
        Options[name] = value;
    else
        sync_cout << "No such option: " << name << sync_endl;
  }

**Comment by alwey** [comment]
Yes, this works. Thank you.

In my opinion Komodo has the most consistent way to handle this so far, as it complies with the communication interface and conveys information that can be logged into debug files.
