### ISSUE TITLE
Yellow patch question

### ISSUE THREAD

**Issue by Nordlandia** [Zerbinati/SugaR#47]
Is all yellow patches merged into source still?

If yes, then i would appreciate if this patch can be merged. 

http://tests.stockfishchess.org/tests/view/59b141130ebc5916ff64aff4

My plan is to test Capablanca's Theorem stating that Q+N duo is trivially stronger than Q+B in the endgame. Testing only work if engine recognize Q+N as marginally better. 

![image](https://user-images.githubusercontent.com/26534454/34909954-f80e15d8-f8ab-11e7-9cc9-ca348c7b4873.png)

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
In begining position Bishop is better.
This position is not far from begining.

I can tell you, that in this position white has a little advantage, even if black to move.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
I consider 1. d4 and 1. e3 to be the main moves.

**Comment by Nordlandia** [comment]
@Kozlov-Sergey-Aleksandrovitch: I think Q+N duo outweighs first move advantage.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
I have set up to analis with Sugar 64.
Will wait 40 iterations (d=40).

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
All depends from pawns structure.
Advantage of knight is, that one bishop is unable to atack knight in half of board squares.
Advantage of bishop is, that bishop can control knight's progress to half of board directions.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
According Sugar, position is between on white to move first +0.00 and +0.07 (here +0.07 is one move advantage).
"First move advantage" is "one move advantage": if variant ends with last white move, than evaluation is +0.07, if variant ands with last black move, than evaluation is +0.00 (considering white to move first).

Every variant should end with equal white's and black's moves.

So: my final avaluation is +0.00.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
[Event "?"]
[Site "?"]
[Date "2018.01.18"]
[Round "?"]
[White ""]
[Black ""]
[Result "1/2-1/2"]
[Comment ""]
[FEN "3qk1n1/pppppppp/8/8/8/8/PPPPPPPP/3QKB2 w - - 0 1"]
[SetUp "1"]

1. e3 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 1... h6 {[%t Ctrl] ^254 ^04 ^00 ^00
^00 } 2. Qg4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 2... Kf8 {[%t Ctrl] ^254 ^04
^00 ^00 ^00 } 3. Qa4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 3... a6 {[%t Ctrl] ^254
^04 ^00 ^00 ^00 } 4. h4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 4... c6 {[%t Ctrl]
^254 ^04 ^00 ^00 ^00 } 5. g4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 5... g5 {[%t
Ctrl] ^254 ^04 ^00 ^00 ^00 } 6. hxg5 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 6...
hxg5 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 7. Qd4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 }
 7... Qc7 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 8. Qd3 {[%t Ctrl] ^254 ^04 ^00 ^00
^00 } 8... Nf6 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 9. Qf5 {[%t Ctrl] ^254 ^04
^00 ^00 ^00 } 9... Qh2 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 10. Qxg5 {[%t Ctrl]
^254 ^04 ^00 ^00 ^00 } 10... Qxf2+ {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 11. Kxf2
{[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 11... Ne4+ {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 }
12. Kf3 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 12... Nxg5+ {[%t Ctrl] ^254 ^04 ^00
^00 ^00 } 13. Kf4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 13... f6 {[%t Ctrl] ^254
^04 ^00 ^00 ^00 } 14. d4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 14... Kf7 {[%t
Ctrl] ^254 ^04 ^00 ^00 ^00 } 15. Bd3 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 15...
d5 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 16. c4 {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 }
16... e5+ {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 17. dxe5 {[%t Ctrl] ^254 ^04 ^00
^00 ^00 } 17... Ne6+ {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 18. Kf5 {[%t Ctrl] ^254
^04 ^00 ^00 ^00 } 18... Ng7+ {[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 19. Kf4
{(0:08:35) 3261388kN}{[%eval 7,40,Sugar 64][%meval 515s]}{1.}{[%t Ctrl] ^254
^04 ^00 ^00 ^00 } 19... Ne6+ {(0:07:38) 2871245kN}{[%eval 0,39,Sugar
64][%meval 458s]}{1.}{[%t Ctrl] ^254 ^04 ^00 ^00 ^00 } 1/2-1/2

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
As i already see, Sugar 64 thinks, that black Q+N has -0.035 Bayes points advantage versus white Q+B.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
I mean Q+N is better than Q+B by 0.035*200 = 7 Bayes points.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Please add this (7 Bayes points to avaluation) to C++ code.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Q+B absolutely equal Q+N.
+0.00 on white to move first and +0.00 on black to move first accourding to me and Sugar.

I prove Sugar's evaluation.

Difference betwen B and N, Q+B and Q+N is in number of such positions in data base.

B==N, Q+B==Q+N.

Done.

**Comment by Nordlandia** [comment]
Larry Kaufman (author of komodo) wrote on talkchess that he use very small bonus for Q+N.

http://talkchess.com/forum/viewtopic.php?t=65093&postdays=0&postorder=asc&topic_view=&start=0

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Q+B absolutely equal Q+N.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
B absolutely equal N.

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Marco, create please a new branch.
Use B_Mg=N_Mg and B_Eg=N_Eg.

And try to update space and pawn structure evaluation combining to pieces mobility.

By now Sugar overvalues B versus N.

Zero calculetes posions number, where white wins and black wins, and normalizes: (W_Points-B_Points)/(W_Points+B_Points). Then Zero bases on norm to evaluate position.

Difference betwen Sugar and Zero is normilization usage to evaluate.

As you know Zero (means normalization) is better, proven by score.

**Comment by Nordlandia** [comment]
What is Bayes point?

And how is it relative to centipawn?

**Comment by Kozlov-Sergey-Aleksandrovitch** [comment]
Bayes offered to calculate side to move in rating.

Bayes points relates to Bayes centipawn.
Elo points relates to Elo centipawn.

**Comment by Nordlandia** [comment]
I really want to test this. Can you fork a copy and merge that yellow patch so i can proceed testing procedure?

**Comment by Nordlandia** [comment]
One guy on ImmortalChess website merged patch into recent SF version.
