### ISSUE TITLE
Compiler errors on Raspberry Pi Linux Stretch

### ISSUE THREAD

**Issue by ScallyBag** [Zerbinati/SugaR#58]
Hi, I’ve pulled your latest code and am having trouble compiling with my usual:
sudo make profile-build ARCH=armv7
It’s never failed before, please advise:

polybook.cpp: In member function ‘void PolyBook::init(const string&)’:
polybook.cpp:352:23: error: ‘fnam’ was not declared in this scope
     FILE *fpt = fopen(fnam, "rb");
                       ^~~~
<builtin>: recipe for target 'polybook.o' failed
make[2]: *** [polybook.o] Error 1
make[2]: Leaving directory '/home/pi/sugaR/source'
Makefile:528: recipe for target 'gcc-profile-make' failed
make[1]: *** [gcc-profile-make] Error 2
make[1]: Leaving directory '/home/pi/sugaR/source'
Makefile:432: recipe for target 'profile-build' failed
make: *** [profile-build] Error 2

Thanks,

Alan Cooper

**Comment by ScallyBag** [comment]
Hi again,

It looks as tho you were refactoring your code for Windows and left the old variable for Linux.

I made the following change in polybook.cpp and it compiles fine:

FILE *fpt = fopen(fnam, "rb");

FILE *fpt = fopen(file_name, "rb");

Cheers,

Al.

**Comment by Zerbinati** [comment]
Problem solved .. very well.
