### ISSUE TITLE
Saving/Loading hash

### ISSUE THREAD

**Issue by hero2017** [Zerbinati/SugaR#87]
I liked Sugar in the past and decided to see if the loading/saving of hash issue has been fixed. I can't believe that in over a year this is still not working.

It may still be related to the limit of it working up to 8 GB or whatever it was before. I use 32 GB on my dual Xeon E5-2699v3 system and although I save hrs of analysis in one position and restart my Aquarium and load the hash in the same position, I still find myself waiting roughly the same amount of time to reach the same depth for the best move.

I think the author needs to look or ask how asmFish does it because this is the only engine that saving/loading hash seems to work best. Raubfisch doesn't have this working either.

When I check in my Windows Resource Monitor I still see that System is loading the hash but where in the past it used to be only System it now, after about a minute of loading the hash, shows the Sugar exe in my Disk tab showing that it's loading the hash....except, it's not...the bytes increase only for System not for Sugar. So something is still really messed up and I can never get it to continue from the depth I saved the hash in.

I really wish this would finally be fixed. Until then I still stick with asmFish for that.

**Comment by Zerbinati** [comment]
I wrote several times to Daniel Jose ..
he had replied that he would solve the problem.
However, it has been a long time.

2018-06-10 4:06 GMT+02:00 hero2017 <notifications@github.com>:

**Comment by hero2017** [comment]
I'm not 100% sure but I think that's what he said last year. Oh well, good engine otherwise. I guess not enough ppl find saving/loading hash useful :-(

**Comment by MichaelB7** [comment]
I never got it to work in McBrain either.
